In [1]:
import numpy as np

E = np.random.randn(10, 4)
print(E)

[[-0.97612931  1.07329834 -0.24470189 -1.68277386]
 [-0.53702335  2.20323933  0.22992928  0.21569279]
 [ 0.26689872 -0.9407565  -0.93314857 -1.25226795]
 [ 0.4354051   0.20998854  1.05989516 -1.31285378]
 [ 0.61786849 -1.15975739  0.18214104  0.10434185]
 [-2.7221402  -1.86274668  1.63217933  1.03559083]
 [-0.12360857  0.03799323 -1.42858987  1.86244805]
 [-0.83861477  1.68425012  0.23856793  0.35204897]
 [-0.45966361  1.48821952 -0.47241813 -0.91366891]
 [-0.28574154 -0.43491601  0.34029161 -1.07995602]]


In [5]:
def embed(indices):
    return(E[indices])

In [6]:
result = embed([2, 3, 3])
print(result)
print(result.mean(axis=0))

[[ 0.26689872 -0.9407565  -0.93314857 -1.25226795]
 [ 0.4354051   0.20998854  1.05989516 -1.31285378]
 [ 0.4354051   0.20998854  1.05989516 -1.31285378]]
[ 0.37923631 -0.17359314  0.39554725 -1.29265851]


In [7]:
one_hot = np.zeros(10)
one_hot[5] = 1
print(one_hot)
print(one_hot @ E)
print(E[5])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[-2.7221402  -1.86274668  1.63217933  1.03559083]
[-2.7221402  -1.86274668  1.63217933  1.03559083]
