In [12]:
import numpy as np

In [ ]:
# Compute the cosine similarity between token 2 and token 5
# cos(θ) = (E[2] @ E[5]) / (||E[2]|| * ||E[5]||)
# If close to 1 → similar, close to 0 → independent

In [14]:
E = np.random.randn(10, 4)

In [15]:
magnitude_a = np.linalg.norm(E[2])
print(magnitude_a)
magnitude_b = np.linalg.norm(E[5])
print(magnitude_b)

1.4672339434989483
2.414701066756274


In [16]:
cos = (E[2] @ E[5]) / (magnitude_a * magnitude_b)

In [17]:
print(cos)

0.24854650997706154


In [18]:
tokens = [3, 4, 6]
print(E[[tokens]])

[[[ 0.59142796  0.06041517 -0.13617145  1.13193454]
  [-1.15421806 -0.7578695   0.47550034 -1.28297646]
  [-0.50361028  0.02817367  1.08771158 -0.75798299]]]


In [19]:
phrase_embeddings = E[tokens]
phrase_vector = phrase_embeddings.mean(axis=0)

print(phrase_embeddings)
print(phrase_vector)
print(phrase_vector.shape)

[[ 0.59142796  0.06041517 -0.13617145  1.13193454]
 [-1.15421806 -0.7578695   0.47550034 -1.28297646]
 [-0.50361028  0.02817367  1.08771158 -0.75798299]]
[-0.35546679 -0.22309356  0.47568015 -0.3030083 ]
(4,)


In [41]:
result = []
query = np.array([0.5, -0.2, 0.1, 0.8])
for e in tokens:
    magnitude_a = np.linalg.norm(query)
    magnitude_b = np.linalg.norm(E[e])
    cos = (query @ E[e]) / (magnitude_a * magnitude_b)
    result.append(cos)

In [ ]:
cos_result = np.array(result)
print(result)
print(f"token most similar : {np.argmax(result)}")

[np.float64(0.942999399007483), np.float64(-0.745151209638279), np.float64(-0.5490261013641661)]
token most smiliar : 0


In [ ]:
# transformer
norms = np.linalg.norm(E, axis=1)
dots = E @ query
similarity = dots / (norms * np.linalg.norm(query))

print(similarity)
print(f"Most similar token {np.argmax(similarity)}")

[ 0.53670032 -0.76506271  0.12847503  0.9429994  -0.74515121 -0.63306495
 -0.5490261   0.5064257   0.21714014  0.22193901]
Most similar token 3
